### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [MSF-Jarvis/KPSConnect#8]
It would be neat to have this available on F-Droid. Would that be possible?

**Comment by MSF-Jarvis** [comment]
Yeah it is possible, but my school's official application doesn't have much
work on an OSS oriented marketplace ¯\_(ツ)_/¯

I'll be preparing an RSS feed reader later this month, maybe that'd be
better for F-Droid?

**Comment by xdevs23** [comment]
F-Droid is full of requests for new apps
It can take ages for an app to be published on fdroid.

**Comment by MSF-Jarvis** [comment]
@xdevs23 I'm not really keen on getting this on F-Droid anyway lol

**Comment by pizzamaker** [comment]
@xdevs23 true, but when the devs themselves send the metadata, the process is much simpler. F-Droid devs just need to build it locally and then upload to their servers :)
